// Bake the MAVLink msgid table (crc_extra, target field offsets) at compile
// time from the vendored dialect XML.
//
// All build-only logic — CRC primitives, the `crc_extra_for_message`
// algorithm, the XML include-graph walker, and the dialect-parse transforms
// — lives under `build_support/` and is `include!`d here.
//
// Output is one generated file in `$OUT_DIR/generated_msgid_table.rs`
// containing `pub(crate) const SORTED: &[(u32, MsgEntry)]` (sorted by msgid),
// included from `src/mavlink/generated.rs`.

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/build_support/crc_extra.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/build_support/xml_loader.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/build_support/dialect_parse.rs"
));

use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};
use time::OffsetDateTime;
use time::format_description::well_known::Rfc3339;

const DIALECTS: &[&str] = &["common.xml", "ardupilotmega.xml"];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_support");

    emit_version_string();

    let xml_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("vendor")
        .join("mavlink");

    let mut entries: HashMap<u32, MsgEntryGen> = HashMap::new();

    for dialect in DIALECTS {
        let path = xml_dir.join(dialect);
        let root = fs::canonicalize(&path)
            .unwrap_or_else(|err| panic!("dialect XML not found: {} ({})", path.display(), err));
        let walk = walk_includes(root, |canon: &PathBuf| -> Result<Vec<PathBuf>, String> {
            println!("cargo:rerun-if-changed={}", canon.display());
            let content = fs::read_to_string(canon).map_err(|err| err.to_string())?;
            let (includes, messages) = parse_xml(&content);
            for msg in messages {
                ingest_message(canon, msg, &mut entries);
            }
            let dir = canon.parent().expect("XML has a parent dir");
            includes
                .into_iter()
                .map(|inc| {
                    let raw = dir.join(&inc);
                    fs::canonicalize(&raw)
                        .map_err(|err| format!("canonicalize include {}: {}", raw.display(), err))
                })
                .collect()
        });
        match walk {
            Ok(()) => {}
            Err(WalkError::Cycle(path)) => {
                panic!("cycle in <include> resolution at {}", path.display());
            }
            Err(WalkError::LoadFailed { key, reason }) => {
                panic!("failed to load {}: {}", key.display(), reason);
            }
        }
    }

    if entries.is_empty() {
        panic!("no MAVLink messages parsed from vendored dialects");
    }
    if !entries.contains_key(&0) {
        panic!("HEARTBEAT (id 0) not found — vendored XML appears incomplete");
    }

    let mut sorted: Vec<(u32, MsgEntryGen)> = entries.into_iter().collect();
    sorted.sort_by_key(|(id, _)| *id);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    let out_path = PathBuf::from(&out_dir).join("generated_msgid_table.rs");
    let mut out = std::io::BufWriter::new(fs::File::create(&out_path).unwrap_or_else(|err| {
        panic!("create {}: {}", out_path.display(), err);
    }));

    writeln!(
        out,
        "// generated by build.rs from {DIALECTS:?} — do not edit"
    )
    .unwrap();
    writeln!(out, "pub(crate) const SORTED: &[(u32, MsgEntry)] = &[").unwrap();
    for (id, entry) in &sorted {
        writeln!(
            out,
            "    ({id}, MsgEntry {{ crc_extra: {crc}, target_sys_offset: {ts:?}, target_comp_offset: {tc:?} }}),",
            id = id,
            crc = entry.crc_extra,
            ts = entry.target_sys_offset,
            tc = entry.target_comp_offset,
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn ingest_message(canon: &Path, msg: ParsedMessage, entries: &mut HashMap<u32, MsgEntryGen>) {
    let crc_extra = {
        let crc_fields: Vec<CrcExtraField<'_>> = msg
            .fields
            .iter()
            .map(|field| CrcExtraField {
                name: &field.name,
                type_name: &field.type_name,
                array_length: field.array_length,
                is_extension: field.is_extension,
            })
            .collect();
        crc_extra_for_message(&msg.name, &crc_fields)
    };
    let (target_sys_offset, target_comp_offset) = compute_offsets(&msg.fields);
    merge_entry(
        msg.id,
        msg.name,
        crc_extra,
        target_sys_offset,
        target_comp_offset,
        entries,
    )
    .unwrap_or_else(|err| panic!("{err} (in {})", canon.display()));
}

fn parse_xml(content: &str) -> (Vec<String>, Vec<ParsedMessage>) {
    let mut reader = Reader::from_str(content);
    reader.config_mut().trim_text(true);

    let mut includes = Vec::new();
    let mut messages = Vec::new();

    let mut in_include = false;
    let mut current_msg: Option<ParsedMessage> = None;
    let mut past_extensions = false;

    loop {
        match reader.read_event() {
            Ok(Event::Start(event)) => {
                let tag = std::str::from_utf8(event.name().as_ref())
                    .expect("tag name not utf8")
                    .to_string();
                match tag.as_str() {
                    "include" => in_include = true,
                    "message" => {
                        let (id, name) = parse_msg_attrs(&event);
                        current_msg = Some(ParsedMessage {
                            id,
                            name,
                            fields: Vec::new(),
                        });
                        past_extensions = false;
                    }
                    "extensions" => {
                        if current_msg.is_some() {
                            past_extensions = true;
                        }
                    }
                    "field" => push_field(&event, current_msg.as_mut(), past_extensions),
                    _ => {}
                }
            }
            Ok(Event::Empty(event)) => {
                let tag = std::str::from_utf8(event.name().as_ref())
                    .expect("tag name not utf8")
                    .to_string();
                match tag.as_str() {
                    "extensions" => {
                        if current_msg.is_some() {
                            past_extensions = true;
                        }
                    }
                    "field" => push_field(&event, current_msg.as_mut(), past_extensions),
                    _ => {}
                }
            }
            Ok(Event::Text(event)) => {
                if in_include {
                    let text = event.unescape().expect("text unescape").trim().to_string();
                    if !text.is_empty() {
                        includes.push(text);
                    }
                }
            }
            Ok(Event::End(event)) => {
                let tag = std::str::from_utf8(event.name().as_ref())
                    .expect("tag name not utf8")
                    .to_string();
                match tag.as_str() {
                    "include" => in_include = false,
                    "message" => {
                        if let Some(msg) = current_msg.take() {
                            messages.push(msg);
                        }
                    }
                    _ => {}
                }
            }
            Ok(Event::Eof) => break,
            Err(err) => panic!("XML parse error: {err}"),
            _ => {}
        }
    }

    (includes, messages)
}

fn parse_msg_attrs(event: &BytesStart<'_>) -> (u32, String) {
    let mut id = 0u32;
    let mut name = String::new();
    for attr_res in event.attributes() {
        let attr = attr_res.expect("attribute parse failed");
        let key = std::str::from_utf8(attr.key.as_ref()).expect("attr key utf8");
        let val = attr.unescape_value().expect("attr value unescape");
        match key {
            "id" => {
                id = val
                    .trim()
                    .parse()
                    .unwrap_or_else(|err| panic!("bad message id '{val}': {err}"));
            }
            "name" => name = val.into_owned(),
            _ => {}
        }
    }
    (id, name)
}

fn push_field(
    event: &BytesStart<'_>,
    current_msg: Option<&mut ParsedMessage>,
    past_extensions: bool,
) {
    if let Some(msg) = current_msg {
        let (type_name, field_name) = parse_field_attrs(event);
        let (elem, len) = parse_array_suffix(&type_name).unwrap_or_else(|err| panic!("{err}"));
        msg.fields.push(ParsedField {
            name: field_name,
            type_name: elem,
            array_length: len,
            is_extension: past_extensions,
        });
    }
}

fn parse_field_attrs(event: &BytesStart<'_>) -> (String, String) {
    let mut type_name = String::new();
    let mut field_name = String::new();
    for attr_res in event.attributes() {
        let attr = attr_res.expect("attribute parse failed");
        let key = std::str::from_utf8(attr.key.as_ref()).expect("attr key utf8");
        let val = attr.unescape_value().expect("attr value unescape");
        match key {
            "type" => type_name = val.into_owned(),
            "name" => field_name = val.into_owned(),
            _ => {}
        }
    }
    (type_name, field_name)
}

fn compute_offsets(fields: &[ParsedField]) -> (Option<u8>, Option<u8>) {
    let mut base: Vec<&ParsedField> = fields.iter().filter(|field| !field.is_extension).collect();
    base.sort_by(|left, right| type_size(&right.type_name).cmp(&type_size(&left.type_name)));

    let mut off: u16 = 0;
    let mut tsys = None;
    let mut tcomp = None;
    for field in &base {
        if field.array_length == 0 && field.type_name == "uint8_t" {
            // MAVLink wire payload length is u8 (max 255), so any valid target
            // field offset fits in u8. Panic on a malformed dialect that places
            // it past byte 255 rather than silently truncating.
            let target_off = u8::try_from(off).unwrap_or_else(|_| {
                panic!(
                    "target field '{}' at offset {} exceeds u8 — payload too large",
                    field.name, off
                )
            });
            if field.name == "target_system" {
                tsys = Some(target_off);
            } else if field.name == "target_component" {
                tcomp = Some(target_off);
            }
        }
        let elem = type_size(&field.type_name) as u16;
        let elem_count = if field.array_length == 0 {
            1u16
        } else {
            field.array_length as u16
        };
        off = off
            .checked_add(elem * elem_count)
            .unwrap_or_else(|| panic!("payload overflow for field '{}'", field.name));
    }
    (tsys, tcomp)
}

/// Compute the value of `RMR_VERSION_STRING` and emit it as a cargo env
/// var consumed by `clap`'s `#[command(version = env!(...))]`.
///
/// Two shapes per the CLAUDE.md "Release strategy" locked decision:
///   - `<X.Y.Z>` when HEAD is exactly the release tag `v<X.Y.Z>` (so
///     `rmr --version` on a tagged-commit build prints just the version).
///   - `<X.Y.Z> (sha <short>, built <RFC 3339 UTC>)` otherwise — a main
///     build between releases disambiguates against the GitHub Release
///     via the short SHA, and the timestamp narrows things further when
///     two unreleased builds share a parent commit.
///
/// Falls back to bare `<X.Y.Z>` when git is not available (cargo install
/// from a source tarball, sandboxed build environments).
fn emit_version_string() {
    let pkg_version = env!("CARGO_PKG_VERSION");
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    let in_git = manifest_dir.join(".git").exists();
    let tagged = in_git && head_matches_release_tag(pkg_version);

    let version_string = if !in_git || tagged {
        pkg_version.to_string()
    } else {
        let short_sha = git_short_sha().unwrap_or_else(|| "unknown".to_string());
        let built = build_timestamp_utc();
        format!("{pkg_version} (sha {short_sha}, built {built})")
    };

    println!("cargo:rustc-env=RMR_VERSION_STRING={version_string}");

    // Rerun when the git ref or working-tree HEAD moves. Best-effort:
    // .git/refs is a directory, so the watch is shallow — fresh commits
    // on the current branch update .git/refs/heads/<branch>, which the
    // shallow watch catches. Packed-refs cases (cloned repos that have
    // packed historical refs) update .git/packed-refs.
    if in_git {
        println!("cargo:rerun-if-changed=.git/HEAD");
        println!("cargo:rerun-if-changed=.git/refs");
        println!("cargo:rerun-if-changed=.git/packed-refs");
    }
}

fn head_matches_release_tag(pkg_version: &str) -> bool {
    let tag = format!("v{pkg_version}");
    let Ok(out) = Command::new("git")
        .args(["describe", "--tags", "--exact-match", "HEAD"])
        .output()
    else {
        return false;
    };
    out.status.success() && String::from_utf8_lossy(&out.stdout).trim() == tag
}

fn git_short_sha() -> Option<String> {
    // Match the SHA width in CLAUDE.md's "Release strategy" example
    // (`sha abc1234, built …`). Git's `--short` default is 7; setting it
    // explicitly documents the intent and survives any future
    // `core.abbrev` config drift.
    let out = Command::new("git")
        .args(["rev-parse", "--short=7", "HEAD"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let trimmed = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed)
    }
}

/// UTC build timestamp formatted as RFC 3339 with second precision (e.g.
/// `2026-05-21T20:15:32Z`). Matches the `ts` field on stats JSON-Lines so
/// the two timestamps can be eyeballed side-by-side.
fn build_timestamp_utc() -> String {
    OffsetDateTime::now_utc()
        .replace_nanosecond(0)
        .unwrap_or_else(|_| OffsetDateTime::now_utc())
        .format(&Rfc3339)
        .unwrap_or_else(|_| "unknown".to_string())
}
