// Bake the MAVLink msgid table (crc_extra, min_payload_len, target field
// offsets) at compile time from the vendored dialect XML.
//
// `crc_extra.rs` is `include!`d at the top of this file so that
// `crc_extra_for_message` (the runtime crate's single source of truth) is also
// what runs here — there is no second implementation to drift.
//
// Output is one generated file in `$OUT_DIR/generated_msgid_table.rs`
// containing `pub(crate) const SORTED: &[(u32, MsgEntry)]` (sorted by msgid),
// included from `src/mavlink/generated.rs`.

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/mavlink/crc_extra.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/build_support/xml_loader.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/build_support/dialect_parse.rs"
));

use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};

const DIALECTS: &[&str] = &["common.xml", "ardupilotmega.xml"];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/mavlink/crc_extra.rs");
    println!("cargo:rerun-if-changed=build_support");
    println!("cargo:rerun-if-changed=build_support/xml_loader.rs");
    println!("cargo:rerun-if-changed=build_support/dialect_parse.rs");

    let xml_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("vendor")
        .join("mavlink");

    let mut entries: HashMap<u32, MsgEntryGen> = HashMap::new();

    for dialect in DIALECTS {
        let p = xml_dir.join(dialect);
        let root = fs::canonicalize(&p)
            .unwrap_or_else(|e| panic!("dialect XML not found: {} ({})", p.display(), e));
        let walk = walk_includes(root, |canon: &PathBuf| -> Result<Vec<PathBuf>, String> {
            println!("cargo:rerun-if-changed={}", canon.display());
            let content = fs::read_to_string(canon).map_err(|e| e.to_string())?;
            let (includes, messages) = parse_xml(&content);
            for msg in messages {
                ingest_message(canon, msg, &mut entries);
            }
            let dir = canon.parent().expect("XML has a parent dir");
            includes
                .into_iter()
                .map(|inc| {
                    let raw = dir.join(&inc);
                    fs::canonicalize(&raw)
                        .map_err(|e| format!("canonicalize include {}: {}", raw.display(), e))
                })
                .collect()
        });
        match walk {
            Ok(()) => {}
            Err(WalkError::Cycle(p)) => {
                panic!("cycle in <include> resolution at {}", p.display());
            }
            Err(WalkError::LoadFailed { key, reason }) => {
                panic!("failed to load {}: {}", key.display(), reason);
            }
        }
    }

    if entries.is_empty() {
        panic!("no MAVLink messages parsed from vendored dialects");
    }
    if !entries.contains_key(&0) {
        panic!("HEARTBEAT (id 0) not found — vendored XML appears incomplete");
    }

    let mut sorted: Vec<(u32, MsgEntryGen)> = entries.into_iter().collect();
    sorted.sort_by_key(|(id, _)| *id);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    let out_path = PathBuf::from(&out_dir).join("generated_msgid_table.rs");
    let mut out = std::io::BufWriter::new(fs::File::create(&out_path).unwrap_or_else(|e| {
        panic!("create {}: {}", out_path.display(), e);
    }));

    writeln!(
        out,
        "// generated by build.rs from {DIALECTS:?} — do not edit"
    )
    .unwrap();
    writeln!(out, "pub(crate) const SORTED: &[(u32, MsgEntry)] = &[").unwrap();
    for (id, e) in &sorted {
        writeln!(
            out,
            "    ({id}, MsgEntry {{ name: {name:?}, crc_extra: {crc}, min_payload_len: {mpl}, target_sys_offset: {ts:?}, target_comp_offset: {tc:?} }}),",
            id = id,
            name = e.name,
            crc = e.crc_extra,
            mpl = e.min_payload_len,
            ts = e.target_sys_offset,
            tc = e.target_comp_offset,
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn ingest_message(canon: &Path, msg: ParsedMessage, entries: &mut HashMap<u32, MsgEntryGen>) {
    let crc_extra = {
        let crc_fields: Vec<CrcExtraField<'_>> = msg
            .fields
            .iter()
            .map(|f| CrcExtraField {
                name: &f.name,
                type_name: &f.type_name,
                array_length: f.array_length,
                is_extension: f.is_extension,
            })
            .collect();
        crc_extra_for_message(&msg.name, &crc_fields)
    };
    let (min_payload_len, target_sys_offset, target_comp_offset) = compute_offsets(&msg.fields);
    merge_entry(
        msg.id,
        msg.name,
        crc_extra,
        min_payload_len,
        target_sys_offset,
        target_comp_offset,
        entries,
    )
    .unwrap_or_else(|e| panic!("{e} (in {})", canon.display()));
}

fn parse_xml(content: &str) -> (Vec<String>, Vec<ParsedMessage>) {
    let mut reader = Reader::from_str(content);
    reader.config_mut().trim_text(true);

    let mut includes = Vec::new();
    let mut messages = Vec::new();

    let mut in_include = false;
    let mut current_msg: Option<ParsedMessage> = None;
    let mut past_extensions = false;

    loop {
        match reader.read_event() {
            Ok(Event::Start(e)) => {
                let tag = std::str::from_utf8(e.name().as_ref())
                    .expect("tag name not utf8")
                    .to_string();
                match tag.as_str() {
                    "include" => in_include = true,
                    "message" => {
                        let (id, name) = parse_msg_attrs(&e);
                        current_msg = Some(ParsedMessage {
                            id,
                            name,
                            fields: Vec::new(),
                        });
                        past_extensions = false;
                    }
                    "extensions" => {
                        if current_msg.is_some() {
                            past_extensions = true;
                        }
                    }
                    "field" => {
                        if let Some(msg) = current_msg.as_mut() {
                            let (type_name, field_name) = parse_field_attrs(&e);
                            let (elem, len) = parse_array_suffix(&type_name)
                                .unwrap_or_else(|err| panic!("{err}"));
                            msg.fields.push(ParsedField {
                                name: field_name,
                                type_name: elem,
                                array_length: len,
                                is_extension: past_extensions,
                            });
                        }
                    }
                    _ => {}
                }
            }
            Ok(Event::Empty(e)) => {
                let tag = std::str::from_utf8(e.name().as_ref())
                    .expect("tag name not utf8")
                    .to_string();
                match tag.as_str() {
                    "extensions" => {
                        if current_msg.is_some() {
                            past_extensions = true;
                        }
                    }
                    "field" => {
                        if let Some(msg) = current_msg.as_mut() {
                            let (type_name, field_name) = parse_field_attrs(&e);
                            let (elem, len) = parse_array_suffix(&type_name)
                                .unwrap_or_else(|err| panic!("{err}"));
                            msg.fields.push(ParsedField {
                                name: field_name,
                                type_name: elem,
                                array_length: len,
                                is_extension: past_extensions,
                            });
                        }
                    }
                    _ => {}
                }
            }
            Ok(Event::Text(e)) => {
                if in_include {
                    let text = e.unescape().expect("text unescape").trim().to_string();
                    if !text.is_empty() {
                        includes.push(text);
                    }
                }
            }
            Ok(Event::End(e)) => {
                let tag = std::str::from_utf8(e.name().as_ref())
                    .expect("tag name not utf8")
                    .to_string();
                match tag.as_str() {
                    "include" => in_include = false,
                    "message" => {
                        if let Some(msg) = current_msg.take() {
                            messages.push(msg);
                        }
                    }
                    _ => {}
                }
            }
            Ok(Event::Eof) => break,
            Err(e) => panic!("XML parse error: {e}"),
            _ => {}
        }
    }

    (includes, messages)
}

fn parse_msg_attrs(e: &BytesStart<'_>) -> (u32, String) {
    let mut id = 0u32;
    let mut name = String::new();
    for attr_res in e.attributes() {
        let attr = attr_res.expect("attribute parse failed");
        let key = std::str::from_utf8(attr.key.as_ref()).expect("attr key utf8");
        let val = attr.unescape_value().expect("attr value unescape");
        match key {
            "id" => {
                id = val
                    .trim()
                    .parse()
                    .unwrap_or_else(|e| panic!("bad message id '{val}': {e}"));
            }
            "name" => name = val.into_owned(),
            _ => {}
        }
    }
    (id, name)
}

fn parse_field_attrs(e: &BytesStart<'_>) -> (String, String) {
    let mut type_name = String::new();
    let mut field_name = String::new();
    for attr_res in e.attributes() {
        let attr = attr_res.expect("attribute parse failed");
        let key = std::str::from_utf8(attr.key.as_ref()).expect("attr key utf8");
        let val = attr.unescape_value().expect("attr value unescape");
        match key {
            "type" => type_name = val.into_owned(),
            "name" => field_name = val.into_owned(),
            _ => {}
        }
    }
    (type_name, field_name)
}

fn compute_offsets(fields: &[ParsedField]) -> (u16, Option<u8>, Option<u8>) {
    let mut base: Vec<&ParsedField> = fields.iter().filter(|f| !f.is_extension).collect();
    base.sort_by(|a, b| type_size(&b.type_name).cmp(&type_size(&a.type_name)));

    let mut off: u16 = 0;
    let mut tsys = None;
    let mut tcomp = None;
    for f in &base {
        if f.array_length == 0 && f.type_name == "uint8_t" {
            // MAVLink wire payload length is u8 (max 255), so any valid target
            // field offset fits in u8. Panic on a malformed dialect that places
            // it past byte 255 rather than silently truncating.
            let target_off = u8::try_from(off).unwrap_or_else(|_| {
                panic!(
                    "target field '{}' at offset {} exceeds u8 — payload too large",
                    f.name, off
                )
            });
            if f.name == "target_system" {
                tsys = Some(target_off);
            } else if f.name == "target_component" {
                tcomp = Some(target_off);
            }
        }
        let elem = type_size(&f.type_name) as u16;
        let n = if f.array_length == 0 {
            1u16
        } else {
            f.array_length as u16
        };
        off = off
            .checked_add(elem * n)
            .unwrap_or_else(|| panic!("payload overflow for field '{}'", f.name));
    }
    (off, tsys, tcomp)
}
